[context.production.environment]
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_API_URI = "https://api.regen.network"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LeqBFIaAAAAAPfLave4lUtLBKF2WYXinbaLNFqB"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"

[context.dev.environment]
NEXT_PUBLIC_SANITY_DATASET = "staging"
NEXT_PUBLIC_API_URI = "https://api-staging.regen.network"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"

[context.deploy-preview.environment]
NEXT_PUBLIC_SANITY_DATASET = "staging"
NEXT_PUBLIC_API_URI = "https://api-staging.regen.network"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=10216"

[[plugins]]
package = "@netlify/plugin-nextjs"
