export const CREATE_SELL_ORDER_HEADER = 'Your sell order was created!';
export const RETIRE_HEADER = 'Your retirement was successful!';
export const PUT_HEADER = 'Your put action was successful!';
export const SEND_HEADER = 'Your send action was successful!';
export const TAKE_HEADER = 'Your take action was successful!';
export const CREATE_SELL_ORDER_TITLE = 'Create Sell Order';
export const CREATE_SELL_ORDER_SHORT = 'Sell';
export const CREATE_SELL_ORDER_BUTTON = 'VIEW ALL SELL ORDERS';
export const ERROR_BUTTON = 'VIEW YOUR PORTFOLIO';
