import { msg } from '@lingui/core/macro';

export const PRIVATE_POST_TITLE = msg`This post has been made private by the project administrator.`;
export const PRIVATE_POST_BODY = msg`Please contact the project admin to request access.`;
export const ALL_POSTS = msg`all posts`;
export const ACTIONS = msg`actions`;
export const SHARE = msg`share`;
export const ADMIN = msg`admin`;
export const REGISTRY = msg`registry`;
export const TIMELINE = msg`Timeline`;
export const SEE_BLOCKCHAIN_RECORD = msg`See the blockchain record`;
export const POST_IS_PRIVATE = msg`Post is private`;
export const PREV = msg`prev`;
export const NEXT = msg`next`;
export const POST_IS_DELETED = msg`Post is deleted`;
export const DRAFT = msg`Draft`;
export const UNTITLED = msg`Untitled`;
export const PRIVATE_FILES_LABEL = msg`Files available on request`;
export const PRIVATE_LOCATIONS_LABEL = msg`Location data available on request`;
export const ADMIN_PRIVATE_LOCATIONS_LABEL = msg`Locations are private`;
export const ADMIN_PRIVATE_FILES_LABEL = msg`Files are private`;
