import { Box } from '@mui/material';
import { InferGetStaticPropsType } from 'next';
import Head from 'next/head';

import BlogSection from '../components/templates/home/Blog/Home.blog';
import CarbonplusSection from '../components/templates/home/CarbonPlus/Home.CarbonPlus';
import ClimateSection from '../components/templates/home/Climate/Home.Climate';
import EcologicalCreditCardsSection from '../components/templates/home/EcologicalCreditCards/Home.EcologicalCreditCards';
import { HomeFoldSection } from '../components/templates/home/HomeFold/Home.HomeFold';
import HomeLedger from '../components/templates/home/Ledger/Home.Ledger';
import MarketplaceSection from '../components/templates/home/Marketplace/Home.Marketplace';
import PartnersSection from '../components/templates/home/Partners/Home.Partners';
import StatsSection from '../components/templates/home/Stats/Home.stats';
import HomeValues from '../components/templates/home/Values/Home.Values';

import {
  BlogSectionDocument,
  BlogSectionQuery,
  CarbonPlusSectionDocument,
  CarbonPlusSectionQuery,
  ClimateSectionDocument,
  ClimateSectionQuery,
  EcologicalCreditCardsSectionDocument,
  EcologicalCreditCardsSectionQuery,
  HomeFoldSectionDocument,
  HomeFoldSectionQuery,
  LedgerSectionDocument,
  LedgerSectionQuery,
  MarketplaceSectionDocument,
  MarketplaceSectionQuery,
  PartnersSectionDocument,
  PartnersSectionQuery,
  StatsSectionDocument,
  StatsSectionQuery,
  ValuesSectionDocument,
  ValuesSectionQuery,
} from '@/generated/sanity-graphql';
import { sanityClient } from '@/lib/clients/sanityClient';

export default function Home({
  homeFoldData,
  carbonPlusData,
  climateData,
  marketplaceData,
  partnersData,
  ecologicalCreditCardsData,
  statsData,
  valuesData,
  ledgerData,
  blogData,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main" sx={{ overflow: 'hidden' }}>
        <HomeFoldSection homeFoldData={homeFoldData} />
        <CarbonplusSection carbonPlusData={carbonPlusData} />
        <ClimateSection climateData={climateData} />
        <MarketplaceSection marketplaceData={marketplaceData} />
        <PartnersSection partnersData={partnersData} />
        <EcologicalCreditCardsSection
          ecologicalCreditCardsData={ecologicalCreditCardsData}
        />
        <StatsSection statsData={statsData} />
        <HomeValues valuesData={valuesData} />
        <HomeLedger ledgerData={ledgerData} />
        <BlogSection blogData={blogData} />
      </Box>
    </>
  );
}

export const getStaticProps = async () => {
  const [
    homeFoldData,
    carbonPlusData,
    climateData,
    marketplaceData,
    partnersData,
    ecologicalCreditCardsData,
    statsData,
    valuesData,
    ledgerData,
    blogData,
  ] = await Promise.all([
    sanityClient.query<HomeFoldSectionQuery>({
      query: HomeFoldSectionDocument,
    }),
    sanityClient.query<CarbonPlusSectionQuery>({
      query: CarbonPlusSectionDocument,
    }),
    sanityClient.query<ClimateSectionQuery>({
      query: ClimateSectionDocument,
    }),
    sanityClient.query<MarketplaceSectionQuery>({
      query: MarketplaceSectionDocument,
    }),
    sanityClient.query<PartnersSectionQuery>({
      query: PartnersSectionDocument,
    }),
    sanityClient.query<EcologicalCreditCardsSectionQuery>({
      query: EcologicalCreditCardsSectionDocument,
    }),
    sanityClient.query<StatsSectionQuery>({
      query: StatsSectionDocument,
    }),
    sanityClient.query<ValuesSectionQuery>({
      query: ValuesSectionDocument,
    }),
    sanityClient.query<LedgerSectionQuery>({
      query: LedgerSectionDocument,
    }),
    sanityClient.query<BlogSectionQuery>({
      query: BlogSectionDocument,
    }),
  ]);

  return {
    props: {
      homeFoldData,
      carbonPlusData,
      climateData,
      marketplaceData,
      partnersData,
      ecologicalCreditCardsData,
      statsData,
      valuesData,
      ledgerData,
      blogData,
    },
  };
};
