[context.production.environment]
NEXT_PUBLIC_SANITY_TAG = "default"
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_SANITY_PROJECT_ID = "jm12rn9t"
NEXT_PUBLIC_BLOCK_EXPLORER = "https://www.mintscan.io"
NEXT_PUBLIC_LEDGER_CHAIN_ID = "regen-1"
NEXT_PUBLIC_SENTRY_ENABLED = "true"
NEXT_PUBLIC_SENTRY_ENVIRONMENT = "production"
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"
NEXT_PUBLIC_BRIDGE_CREDIT_CLASS_ID = "C03"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-6ZGJM8JXYN"
NEXT_PUBLIC_SKIPPED_CLASS_ID = "C01"
NEXT_PUBLIC_DEPLOY_CONTEXT = "production"
NEXT_PUBLIC_CW_ADMIN_FACTORY_ADDR = "regen18cszlvm6pze0x9sz32qnjq4vtd45xehqs8dq7cwy8yhq35wfnn3qz4kya2"
NEXT_PUBLIC_DAODAO_CORE_CODE_ID = "25"
NEXT_PUBLIC_FILTER_CODE_ID = "39"
NEXT_PUBLIC_PROTOCOLBUF_REGISTRY_CODE_ID = "40"
NEXT_PUBLIC_RBAM_CODE_ID = "41"
NEXT_PUBLIC_PROPOSAL_SINGLE_CODE_ID = "32"
NEXT_PUBLIC_PRE_PROPOSE_SINGLE_CODE_ID = "30"
NEXT_PUBLIC_CW4_GROUP_CODE_ID = "2"
NEXT_PUBLIC_DAO_VOTING_CW4_CODE_ID = "35"
NEXT_PUBLIC_IMAGE_STORAGE_BASE_URL = "https://regen-registry.s3.amazonaws.com/"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_AMPLITUDE_API_KEY = "804411ae5b6e49e09e76d968a4193ae3"
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = "d6fdf2c8dd645ff3e6b444e551890c2b"
NEXT_PUBLIC_WEBSITE_URL = "https://www.regen.network"
NEXT_PUBLIC_BRIDGE_BASKET = "eco.uC.NCT"

[context.dev.environment]
NEXT_PUBLIC_SANITY_DATASET = "staging"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_LEDGER_CHAIN_ID = "regen-upgrade"
NEXT_PUBLIC_LEDGER_CHAIN_NAME = "Regen - Upgrade Testnet"
NEXT_PUBLIC_BLOCK_EXPLORER = "https://explorer-regen-upgrade.vitwit.com"
NEXT_PUBLIC_SENTRY_ENVIRONMENT = "development"
NEXT_PUBLIC_BRIDGE_CREDIT_CLASS_ID = "C03"
NEXT_PUBLIC_BRIDGE = "true"
NEXT_PUBLIC_SKIPPED_CLASS_ID = ""
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"
NEXT_PUBLIC_DEPLOY_CONTEXT = "development"
NEXT_PUBLIC_AMPLITUDE_API_KEY = "804411ae5b6e49e09e76d968a4193ae3"
NEXT_PUBLIC_DEFAULT_COMMUNITY_PROJECTS_FILTER = "true"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-9ENS4JTCWY"
NEXT_PUBLIC_IMAGE_STORAGE_BASE_URL = "https://regen-registry.s3.amazonaws.com/"
NEXT_PUBLIC_SANITY_PROJECT_ID = "jm12rn9t"
NEXT_PUBLIC_SANITY_TAG = "default"
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = "d6fdf2c8dd645ff3e6b444e551890c2b"
NEXT_PUBLIC_WEBSITE_URL = "https://www.regen.network"
NEXT_PUBLIC_CW_ADMIN_FACTORY_ADDR = "regen1cpewugrc7gx9lx9qf63ahxsslhs004zvdfuagdunfpfqzxn3fnyq5drgqn"
NEXT_PUBLIC_DAODAO_CORE_CODE_ID = "25"
NEXT_PUBLIC_FILTER_CODE_ID = "39"
NEXT_PUBLIC_PROTOCOLBUF_REGISTRY_CODE_ID = "40"
NEXT_PUBLIC_RBAM_CODE_ID = "41"
NEXT_PUBLIC_PROPOSAL_SINGLE_CODE_ID = "32"
NEXT_PUBLIC_PRE_PROPOSE_SINGLE_CODE_ID = "30"
NEXT_PUBLIC_CW4_GROUP_CODE_ID = "2"
NEXT_PUBLIC_DAO_VOTING_CW4_CODE_ID = "35"
NEXT_PUBLIC_BRIDGE_BASKET = "eco.uC.NCT"

# Main build configuration
[build]
base = "web-marketplace"
command = "bun run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"


[context.deploy-preview.environment]
NEXT_PUBLIC_SANITY_DATASET = "staging"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_LEDGER_CHAIN_ID = "regen-upgrade"
NEXT_PUBLIC_LEDGER_CHAIN_NAME = "Regen - Upgrade Testnet"
NEXT_PUBLIC_BLOCK_EXPLORER = "https://explorer-regen-upgrade.vitwit.com"
NEXT_PUBLIC_SENTRY_ENVIRONMENT = "development"
NEXT_PUBLIC_BRIDGE_CREDIT_CLASS_ID = "C03"
NEXT_PUBLIC_BRIDGE = "true"
NEXT_PUBLIC_SKIPPED_CLASS_ID = ""
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"
NEXT_PUBLIC_DEPLOY_CONTEXT = "development"
NEXT_PUBLIC_AMPLITUDE_API_KEY = "804411ae5b6e49e09e76d968a4193ae3"
NEXT_PUBLIC_DEFAULT_COMMUNITY_PROJECTS_FILTER = "true"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-9ENS4JTCWY"
NEXT_PUBLIC_IMAGE_STORAGE_BASE_URL = "https://regen-registry.s3.amazonaws.com/"
NEXT_PUBLIC_SANITY_PROJECT_ID = "jm12rn9t"
NEXT_PUBLIC_SANITY_TAG = "default"
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID = "d6fdf2c8dd645ff3e6b444e551890c2b"
NEXT_PUBLIC_WEBSITE_URL = "https://www.regen.network"
NEXT_PUBLIC_CW_ADMIN_FACTORY_ADDR = "regen1cpewugrc7gx9lx9qf63ahxsslhs004zvdfuagdunfpfqzxn3fnyq5drgqn"
NEXT_PUBLIC_DAODAO_CORE_CODE_ID = "25"
NEXT_PUBLIC_FILTER_CODE_ID = "39"
NEXT_PUBLIC_PROTOCOLBUF_REGISTRY_CODE_ID = "40"
NEXT_PUBLIC_RBAM_CODE_ID = "41"
NEXT_PUBLIC_PROPOSAL_SINGLE_CODE_ID = "32"
NEXT_PUBLIC_PRE_PROPOSE_SINGLE_CODE_ID = "30"
NEXT_PUBLIC_CW4_GROUP_CODE_ID = "2"
NEXT_PUBLIC_DAO_VOTING_CW4_CODE_ID = "35"
NEXT_PUBLIC_BRIDGE_BASKET = "eco.uC.NCT"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=10216"

# makes the plugin print the 20 biggest files in every handler
NEXT_NETLIFY_DEBUG = "true"
# shows everything the build system is doing
NETLIFY_BUILD_DEBUG = "true"

[[redirects]]
from = "https://app.regen.network/create-methodology"
to = "https://app.regen.network"
force = true
status = 302


[[redirects]]
from = "https://app.regen.network/create-methodology/methodology-review-process"
to = "https://app.regen.network"
force = true
status = 302

[[redirects]]
from = "https://app.regen.network/buyers/"
to = "https://www.regen.network/buyers"
force = true
status = 302

[[redirects]]
from = "https://app.regen.network/ecocredits/*"
to = "https://app.regen.network/dashboard/:splat"
force = true
status = 302

[[redirects]]
from = "https://app.regen.network/ecocredits/accounts/*"
to = "https://app.regen.network/profiles/:splat"
force = true
status = 302

# Netlify internals (Image CDN lives under /.netlify/*)
[[redirects]]
from = "/.netlify/*"
to = "/.netlify/:splat"
status = 200

[functions]
included_files = ["!node_modules/canvas/**/*"]
