[context.production.environment]
NEXT_PUBLIC_SANITY_TAG = "default"
NEXT_PUBLIC_SANITY_DATASET = "production"
NEXT_PUBLIC_BLOCK_EXPLORER = "https://www.mintscan.io"
NEXT_PUBLIC_LEDGER_CHAIN_ID = "regen-1"
NEXT_PUBLIC_SENTRY_ENABLED = "true"
NEXT_PUBLIC_SENTRY_ENVIRONMENT = "production"
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"
NEXT_PUBLIC_BRIDGE_CREDIT_CLASS_ID = "C03"
NEXT_PUBLIC_GA_MEASUREMENT_ID = "G-6ZGJM8JXYN"
NEXT_PUBLIC_TOUCAN_LINK = "https://toucan.earth/overview?chainId=137"
NEXT_PUBLIC_SKIPPED_CLASS_ID = "C01"
NEXT_PUBLIC_DEPLOY_CONTEXT = "production"
NEXT_PUBLIC_CW_ADMIN_FACTORY_ADDR = "regen18cszlvm6pze0x9sz32qnjq4vtd45xehqs8dq7cwy8yhq35wfnn3qz4kya2"
NEXT_PUBLIC_DAODAO_CORE_CODE_ID = "25"
NEXT_PUBLIC_FILTER_CODE_ID = "39"
NEXT_PUBLIC_PROTOCOLBUF_REGISTRY_CODE_ID = "40"
NEXT_PUBLIC_RBAM_CODE_ID = "41"
NEXT_PUBLIC_PROPOSAL_SINGLE_CODE_ID = "32"
NEXT_PUBLIC_PRE_PROPOSE_SINGLE_CODE_ID = "27"
NEXT_PUBLIC_CW4_GROUP_CODE_ID = "2"
NEXT_PUBLIC_DAO_VOTING_CW4_CODE_ID = "35"

[context.dev.environment]
NEXT_PUBLIC_SANITY_TAG = "default"
NEXT_PUBLIC_SANITY_DATASET = "staging"
NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_LEDGER_CHAIN_ID = "regen-upgrade"
NEXT_PUBLIC_LEDGER_CHAIN_NAME = "Regen - Upgrade Testnet"
NEXT_PUBLIC_BLOCK_EXPLORER = "https://explorer-regen-upgrade.vitwit.com"
NEXT_PUBLIC_SENTRY_ENVIRONMENT = "development"
NEXT_PUBLIC_TOUCAN_LINK = "https://test.app.toucan.earth/?chainId=137"
NEXT_PUBLIC_BRIDGE_API_URI = "https://toucan-bridge-staging.herokuapp.com"
NEXT_PUBLIC_BRIDGE_CREDIT_CLASS_ID = "C56"
NEXT_PUBLIC_BRIDGE = "true"
NEXT_PUBLIC_SKIPPED_CLASS_ID = ""
NEXT_PUBLIC_DEPLOY_CONTEXT = "development"
NEXT_PUBLIC_CW_ADMIN_FACTORY_ADDR = "regen1hrpna9v7vs3stzyd4z3xf00676kf78zpe2u5ksvljswn2vnjp3ysp76v39"
NEXT_PUBLIC_DAODAO_CORE_CODE_ID = "6"
NEXT_PUBLIC_FILTER_CODE_ID = "14"
NEXT_PUBLIC_PROTOCOLBUF_REGISTRY_CODE_ID = "15"
NEXT_PUBLIC_RBAM_CODE_ID = "16"
NEXT_PUBLIC_PROPOSAL_SINGLE_CODE_ID = "13"
NEXT_PUBLIC_PRE_PROPOSE_SINGLE_CODE_ID = "11"
NEXT_PUBLIC_CW4_GROUP_CODE_ID = "2"
NEXT_PUBLIC_DAO_VOTING_CW4_CODE_ID = "19"

# Build settings for Next.js deploy previews
[context.deploy-preview]
  command = "bun run build"
  publish = "web-marketplace/dist"

[[context.deploy-preview.plugins]]
  package = "@netlify/plugin-nextjs"


[context.deploy-preview.environment]

NEXT_PUBLIC_RECAPTCHA_SITE_KEY = "6LchxlAaAAAAANjtO3w4b5ihVCL87tYfbe0ltzp9"
NEXT_PUBLIC_INTERCOM_APP_ID = "kn5di10s"
NEXT_PUBLIC_LEDGER_CHAIN_ID = "regen-upgrade"
NEXT_PUBLIC_LEDGER_CHAIN_NAME = "Regen - Upgrade Testnet"
NEXT_PUBLIC_BLOCK_EXPLORER = "https://explorer-regen-upgrade.vitwit.com"
NEXT_PUBLIC_SENTRY_ENVIRONMENT = "development"
NEXT_PUBLIC_TOUCAN_LINK = "https://test.app.toucan.earth/?chainId=137"
NEXT_PUBLIC_BRIDGE_API_URI = "https://toucan-bridge-staging.herokuapp.com"
NEXT_PUBLIC_BRIDGE_CREDIT_CLASS_ID = "C56"
NEXT_PUBLIC_BRIDGE = "true"
NEXT_PUBLIC_SKIPPED_CLASS_ID = ""
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"
NEXT_PUBLIC_DEPLOY_CONTEXT = "development"
NEXT_PUBLIC_CW_ADMIN_FACTORY_ADDR = "regen1hrpna9v7vs3stzyd4z3xf00676kf78zpe2u5ksvljswn2vnjp3ysp76v39"
NEXT_PUBLIC_DAODAO_CORE_CODE_ID = "6"
NEXT_PUBLIC_FILTER_CODE_ID = "14"
NEXT_PUBLIC_PROTOCOLBUF_REGISTRY_CODE_ID = "15"
NEXT_PUBLIC_RBAM_CODE_ID = "16"
NEXT_PUBLIC_PROPOSAL_SINGLE_CODE_ID = "13"
NEXT_PUBLIC_PRE_PROPOSE_SINGLE_CODE_ID = "11"
NEXT_PUBLIC_CW4_GROUP_CODE_ID = "2"
NEXT_PUBLIC_DAO_VOTING_CW4_CODE_ID = "19"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@keplr-wallet",
    "@ledgerhq/hw-app-eth",
    "@ethereumjs",
    "mapbox-gl"
  ]

[build.environment]
NODE_OPTIONS = "--max-old-space-size=10216"

[[redirects]]
from = "https://app.regen.network/create-methodology"
to = "https://app.regen.network"
force = true
status = 302


[[redirects]]
from = "https://app.regen.network/create-methodology/methodology-review-process"
to = "https://app.regen.network"
force = true
status = 302

[[redirects]]
from = "https://app.regen.network/buyers/"
to = "https://www.regen.network/buyers"
force = true
status = 302

[[redirects]]
from = "https://app.regen.network/ecocredits/*"
to = "https://app.regen.network/dashboard/:splat"
force = true
status = 302

[[redirects]]
from = "https://app.regen.network/ecocredits/accounts/*"
to = "https://app.regen.network/profiles/:splat"
force = true
status = 302
