import {
  URL_REGISTRY_MARKETPLACE_LEGAL,
  URL_REGISTRY_TERMS_SERVICE,
  URL_WEB_PRIVACY,
} from 'web-components/lib/utils/globals';

export const URL_PRIVACY = URL_WEB_PRIVACY;
export const URL_TERMS_SERVICE = URL_REGISTRY_TERMS_SERVICE;
export const URL_MARKETPLACE_LEGAL = URL_REGISTRY_MARKETPLACE_LEGAL;
