/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.13.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  dao?: string | null;
  enabled?: boolean | null;
  filter_code_id: number;
  filter_salt?: Binary | null;
  initial_roles?: InitialRole[] | null;
  owner?: string | null;
  protobuf_registry_code_id?: number | null;
  protobuf_registry_salt?: Binary | null;
}
export interface InitialRole {
  assignments?: string[] | null;
  authorizations?: InitialAuthorization[] | null;
  enabled?: boolean | null;
  metadata?: string | null;
  name: string;
}
export interface InitialAuthorization {
  enabled?: boolean | null;
  filter?: {
    [k: string]: unknown;
  };
  metadata?: string | null;
  name: string;
  skip_prepare?: boolean | null;
}
export type ExecuteMsg = {
  update_dao: {
    dao: string;
  };
} | {
  update_filter: {
    filter: ModuleUpdate;
  };
} | {
  update_protobuf_registry: {
    protobuf_registry?: ModuleUpdate | null;
  };
} | {
  update_enabled: {
    enabled: boolean;
  };
} | {
  execute_protobuf_registry: ExecuteMsg1;
} | {
  create_role: {
    assignments?: string[] | null;
    authorizations?: InitialAuthorization[] | null;
    enabled?: boolean | null;
    metadata?: string | null;
    name: string;
  };
} | {
  update_role: {
    enabled?: boolean | null;
    metadata?: UpdateForString | null;
    name?: string | null;
    role_id: number;
  };
} | {
  create_authorization: {
    enabled?: boolean | null;
    filter?: {
      [k: string]: unknown;
    };
    metadata?: string | null;
    name: string;
    role_id: number;
    skip_prepare?: boolean | null;
  };
} | {
  update_authorization: {
    authorization_id: number;
    enabled?: boolean | null;
    filter?: UpdateForAnyValue | null;
    metadata?: UpdateForString | null;
    name?: string | null;
    skip_prepare?: boolean | null;
  };
} | {
  assign: {
    assign: Assignment[];
  };
} | {
  revoke: {
    revoke: Assignment[];
  };
} | {
  execute_actions: {
    actions: ActionToExecute[];
  };
} | {
  update_ownership: Action;
};
export type ModuleUpdate = {
  new: ModuleInstantiateInfo;
} | {
  existing: {
    address: string;
  };
};
export type Admin = {
  address: {
    addr: string;
  };
} | {
  core_module: {};
};
export type Uint128 = string;
export type ExecuteMsg1 = {
  register: {
    file_descriptor_sets: number[][];
  };
} | {
  unregister: {
    file_names: string[];
    message_limit?: number | null;
  };
} | {
  prepare: {
    messages: string[];
  };
} | {
  unprepare: {
    messages: string[];
  };
} | {
  update_ownership: Action;
};
export interface Action {
  addr: Addr;
  authorization_id: number;
  height: number;
  id: number;
  msg: CosmosMsgForEmpty;
  role_id: number;
  tx_index?: number | null;
}
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type UpdateForString = "clear" | {
  set: string;
};
export type UpdateForAnyValue = "clear" | {
  set: true;
};
export type CosmosMsgForEmpty = {
  bank: BankMsg;
} | {
  custom: Empty;
} | {
  staking: StakingMsg;
} | {
  distribution: DistributionMsg;
} | {
  stargate: {
    type_url: string;
    value: Binary;
    [k: string]: unknown;
  };
} | {
  ibc: IbcMsg;
} | {
  wasm: WasmMsg;
} | {
  gov: GovMsg;
};
export type BankMsg = {
  send: {
    amount: Coin[];
    to_address: string;
    [k: string]: unknown;
  };
} | {
  burn: {
    amount: Coin[];
    [k: string]: unknown;
  };
};
export type StakingMsg = {
  delegate: {
    amount: Coin;
    validator: string;
    [k: string]: unknown;
  };
} | {
  undelegate: {
    amount: Coin;
    validator: string;
    [k: string]: unknown;
  };
} | {
  redelegate: {
    amount: Coin;
    dst_validator: string;
    src_validator: string;
    [k: string]: unknown;
  };
};
export type DistributionMsg = {
  set_withdraw_address: {
    address: string;
    [k: string]: unknown;
  };
} | {
  withdraw_delegator_reward: {
    validator: string;
    [k: string]: unknown;
  };
};
export type IbcMsg = {
  transfer: {
    amount: Coin;
    channel_id: string;
    timeout: IbcTimeout;
    to_address: string;
    [k: string]: unknown;
  };
} | {
  send_packet: {
    channel_id: string;
    data: Binary;
    timeout: IbcTimeout;
    [k: string]: unknown;
  };
} | {
  close_channel: {
    channel_id: string;
    [k: string]: unknown;
  };
};
export type WasmMsg = {
  execute: {
    contract_addr: string;
    funds: Coin[];
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  instantiate: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  instantiate2: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
    salt: Binary;
    [k: string]: unknown;
  };
} | {
  migrate: {
    contract_addr: string;
    msg: Binary;
    new_code_id: number;
    [k: string]: unknown;
  };
} | {
  update_admin: {
    admin: string;
    contract_addr: string;
    [k: string]: unknown;
  };
} | {
  clear_admin: {
    contract_addr: string;
    [k: string]: unknown;
  };
};
export type GovMsg = {
  vote: {
    proposal_id: number;
    vote: VoteOption;
    [k: string]: unknown;
  };
} | {
  vote_weighted: {
    options: WeightedVoteOption[];
    proposal_id: number;
    [k: string]: unknown;
  };
};
export type VoteOption = "yes" | "no" | "abstain" | "no_with_veto";
export type Decimal = string;
export interface ModuleInstantiateInfo {
  admin?: Admin | null;
  code_id: number;
  funds?: Coin[] | null;
  label: string;
  msg: Binary;
  salt?: Binary | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface Assignment {
  addr: string;
  role_id: number;
}
export interface ActionToExecute {
  authorization_id: number;
  msg: CosmosMsgForEmpty;
}
export interface Empty {
  [k: string]: unknown;
}
export interface IbcTimeout {
  block?: IbcTimeoutBlock | null;
  timestamp?: Timestamp | null;
  [k: string]: unknown;
}
export interface IbcTimeoutBlock {
  height: number;
  revision: number;
  [k: string]: unknown;
}
export interface WeightedVoteOption {
  option: VoteOption;
  weight: Decimal;
  [k: string]: unknown;
}
export type QueryMsg = {
  info: {};
} | {
  dao: {};
} | {
  filter: {};
} | {
  protobuf_registry: {};
} | {
  enabled: {};
} | {
  role: {
    id: number;
  };
} | {
  list_roles: {
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  authorization: {
    id: number;
  };
} | {
  list_authorizations: {
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  list_authorizations_by_role: {
    limit?: number | null;
    role_id: number;
    start_after?: number | null;
  };
} | {
  assigned: {
    addr: string;
    role_id: number;
  };
} | {
  list_assignments: {
    limit?: number | null;
    start_after?: [string, number] | null;
  };
} | {
  list_addresses_with_role: {
    limit?: number | null;
    role_id: number;
    start_after?: string | null;
  };
} | {
  list_roles_for_address: {
    addr: string;
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  action: {
    id: number;
  };
} | {
  list_actions: {
    limit?: number | null;
    reverse?: boolean | null;
    start_after?: number | null;
  };
} | {
  list_actions_by_role: {
    limit?: number | null;
    reverse?: boolean | null;
    role_id: number;
    start_after?: number | null;
  };
} | {
  list_actions_by_authorization: {
    authorization_id: number;
    limit?: number | null;
    reverse?: boolean | null;
    start_after?: number | null;
  };
} | {
  list_actions_by_address: {
    addr: string;
    limit?: number | null;
    reverse?: boolean | null;
    start_after?: number | null;
  };
} | {
  authorized: {
    addr: string;
    limit?: number | null;
    msg: CosmosMsgForEmpty;
    start_after?: [number, number] | null;
  };
} | {
  authorized_by_role: {
    addr: string;
    limit?: number | null;
    msg: CosmosMsgForEmpty;
    role_id: number;
    start_after?: number | null;
  };
} | {
  authorized_by: {
    addr: string;
    authorization_id: number;
    msg: CosmosMsgForEmpty;
  };
} | {
  test_filter: {
    filter: true;
    msg: CosmosMsgForEmpty;
  };
} | {
  ownership: {};
};
export interface MigrateMsg {}
export type Addr = string;
export interface ActionResponse {
  action: Action;
}
export interface AssignedResponse {
  assigned: boolean;
}
export interface AuthorizationResponse {
  authorization: Authorization;
}
export interface Authorization {
  enabled: boolean;
  filter?: {
    [k: string]: unknown;
  };
  id: number;
  metadata?: string | null;
  name: string;
  role_id: number;
}
export type AuthorizedResponse = {
  authorized: {
    authorization: Authorization;
    role: Role;
  };
} | {
  unauthorized: {
    last_checked?: [number, number] | null;
    reason: string;
  };
};
export interface Role {
  enabled: boolean;
  id: number;
  metadata?: string | null;
  name: string;
}
export type AuthorizedByResponse = {
  authorized: {
    authorization: Authorization;
    role: Role;
  };
} | {
  unauthorized: {
    reason: string;
  };
};
export type AuthorizedByRoleResponse = {
  authorized: {
    authorization: Authorization;
    role: Role;
  };
} | {
  unauthorized: {
    last_checked?: number | null;
    reason: string;
  };
};
export interface DaoResponse {
  dao: Addr;
}
export interface EnabledResponse {
  enabled: boolean;
}
export interface FilterResponse {
  filter: Addr;
}
export interface InfoResponse {
  info: ContractVersion;
}
export interface ContractVersion {
  contract: string;
  version: string;
}
export interface ListActionsResponse {
  actions: Action[];
}
export interface ListAddressesWithRoleResponse {
  addresses: Addr[];
}
export interface ListAssignmentsResponse {
  assignments: Assignment[];
}
export interface ListAuthorizationsResponse {
  authorizations: Authorization[];
}
export interface ListRolesResponse {
  roles: Role[];
}
export interface ListRolesForAddressResponse {
  role_ids: number[];
}
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}
export interface ProtobufRegistryResponse {
  protobuf_registry?: Addr | null;
}
export interface RoleResponse {
  role: Role;
}
export type TestFilterResponse = {
  pass: {};
} | {
  fail: {
    reason: string;
  };
};