/* eslint-disable lingui/no-unlocalized-strings */
import { Member } from '../BaseMembersTable/BaseMembersTable.types';

export const mockMembers: Member[] = [
  {
    id: '1',
    name: 'Jane Smith',
    email: 'jane@example.com',
    title: 'Project Manager',
    organization: 'Ecometric',
    role: 'admin',
    onChainRoleId: 2,
    avatar: 'https://i.pravatar.cc/299',
    visible: true,
    hasWalletAddress: true,
    isCurrentUser: false,
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'john@example.com',
    title: 'Project Manager',
    organization: 'Ecometric',
    role: 'editor',
    onChainRoleId: 4,
    avatar: 'https://i.pravatar.cc/300',
    visible: false,
    hasWalletAddress: true,
    isCurrentUser: false,
  },
  {
    id: '3',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    title: 'Project Manager',
    organization: 'Ecometric',
    role: 'viewer',
    onChainRoleId: 5,
    avatar: 'https://i.pravatar.cc/301',
    visible: true,
    hasWalletAddress: false,
    isCurrentUser: false,
  },
  {
    id: '4',
    name: 'Bob Brown',
    email: 'bob@example.com',
    title: 'Project Manager',
    organization: 'Ecometric',
    role: 'owner',
    onChainRoleId: 2,
    avatar: 'https://i.pravatar.cc/302',
    visible: true,
    hasWalletAddress: true,
    isCurrentUser: true,
  },
];

export const mockAccounts = [
  {
    id: 'acc-1',
    creatorId: 'creator-1',
    name: 'Alice Regeneros',
    type: 'individual',
    image: 'https://i.pravatar.cc/300',
    description: 'Forest project lead',
    addr: 'regen1aliceaddressxyz',
    accountTranslationsById: { nodes: [] },
  },
  {
    id: 'acc-2',
    creatorId: 'creator-2',
    name: 'Bob Carbon',
    type: 'individual',
    image: 'https://i.pravatar.cc/299',
    description: 'Soil data analyst',
    addr: 'regen1bobcarbonaddr',
    accountTranslationsById: { nodes: [] },
  },
  {
    id: 'acc-3',
    creatorId: 'creator-3',
    name: 'Carol Ecosystem',
    type: 'organization',
    image: 'https://i.pravatar.cc/288',
    description: 'Biodiversity NGO',
    addr: 'regen1carolorgaddr',
    accountTranslationsById: { nodes: [] },
  },
  {
    id: 'acc-4',
    creatorId: 'creator-4',
    name: 'Dave Verifier',
    type: 'individual',
    image: 'https://i.pravatar.cc/320',
    description: 'Independent verifier',
    addr: 'regen1daveverifier',
    accountTranslationsById: { nodes: [] },
  },
];
